### ISSUE TITLE
Windows issues

### ISSUE THREAD

**Issue by runfaj** [erik/alexacast#2]
Would love to have an option available for windows. However, it seems that it never gets past the openssl and cryptography parts on the requirements install.

**Comment by erik** [comment]
Hi @runfaj, thanks for reporting!

I don't have access to a Windows machine, so I won't be able to reproduce the install issue myself, but I can try to help you figure out the problem. Could you share what errors you're running into and any relevant console output?

**Comment by tsanthoshreddy** [comment]
is this project complete? running alexacast does it control chromecast?

**Comment by tsanthoshreddy** [comment]
I was wondering how do we add skill for chromecast in alexa

**Comment by erik** [comment]
Hi @runfaj, I'm going through my projects closing old issues. 

If this problem is still relevant to you (or anyone else who comes across this page) please feel free to reopen!
