### ISSUE TITLE
[Feature Request] E2E Alexa ChromeCast support

### ISSUE THREAD

**Issue by msaroufim** [erik/alexacast#7]
Hey there,

Am wondering if there are any plans in the pipeline to support an E2E integration where you could tell Alexa something like:

"Play Stranger Things on Netflix"
"Play Attack on Titan on CrunchyRoll"

I don't have much Alexa development experience but am happy to help under your guidance.

**Comment by erik** [comment]
Hmm, I'd have to look more into this but _I think_ this wouldn't be possible. 

As far as I know, for something like Netflix (or crunchyroll), it would have to be the official app that initiates the chromecast connection, and then alexacast could only operate as a voice activated remote control. 

Would love to be proven wrong on this though!

**Comment by msaroufim** [comment]
Understood. Thanks Erik!
