### ISSUE TITLE
Skill setup step

### ISSUE THREAD

**Issue by khmyznikov** [erik/alexacast#8]
Could you please explain last step. I see what server works, but how to setup skill for Alexa?

**Comment by erik** [comment]
Hi @khmyznikov, sorry for the subpar documentation. Unfortunately people seem to have found this repo after I stopped having access to an Alexa device.

Anyway.

1. Run the server, make sure it has an SSL certificate and is exposed to the world ([see here](https://github.com/erik/alexandra#setting-up-a-web-server))
2. Set up your skill in the [developer console](https://developer.amazon.com/edw/home.html#/skills)
3. Copy paste the [intent schema](https://github.com/erik/alexacast/blob/master/intents.json)
4. Copy paste the [utterances.txt](https://github.com/erik/alexacast/blob/master/utterances.txt) into the "Enter Values" field on the "Interaction Model" tab
5. Test it out, make sure it works.

These steps are mostly from memory, so please let me know if you're successful and I can add the instructions to the README

**Comment by khmyznikov** [comment]
@erik "Unable to reach the requested skill". I'm need a real ip address? My ip and skill port should be in aws skill Configuration as https? 
SSL type: 
-  My development endpoint has a certificate from a trusted certificate authority
-  My development endpoint is a sub-domain of a domain that has a wildcard certificate from a certificate authority
-  I will upload a self-signed certificate in X.509 format.

**Comment by erik** [comment]
Hi @khmyznikov, 

Because you need to use HTTPS, you'll need a domain name (or subdomain) that points at your home's external IP. You can either self sign a certificate (which would be the third bullet point) or use something like [LetsEncrypt](https://letsencrypt.org/) (which would be the first bullet point).

**Comment by erik** [comment]
Hi @khmyznikov, do you still need help with this?

**Comment by khmyznikov** [comment]
Yes, but I have not real IP address and can't setup it for now. Maybe I can imitate it by VPN but it not easy to setup for one network port only.On 28 Feb 2018 4:50 am, Erik Price <notifications@github.com> wrote:Hi @khmyznikov, do you still need help with this?

**Comment by erik** [comment]
Closing this issue out due to inactivity, please feel free to reopen if there is still an issue!
